-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 0.9.4
-- PostgreSQL version: 13.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- Database creation must be performed outside a multi lined SQL file. 
-- These commands were put in this file only as a convenience.
-- 
-- object: new_database | type: DATABASE --
-- DROP DATABASE IF EXISTS new_database;
CREATE DATABASE PROJETO_UESC;
-- ddl-end --


-- object: public."TBL_UNIVERSIDADE" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_UNIVERSIDADE" CASCADE;
CREATE TABLE public."TBL_UNIVERSIDADE" (
	"ID_UNI" smallint NOT NULL,
	"NOME_UNI" varchar(100) NOT NULL,
	"ENDERECO_UNI" varchar(100) NOT NULL,
	"CEP_UNI" varchar(50) NOT NULL,
	"CIDADE_UNI" varchar(50) NOT NULL,
	"ESTADO_UNI" varchar(2) NOT NULL,
	"ID_CON_TBL_CONSU" smallint NOT NULL,
	CONSTRAINT "TBL_UNIVERSIDADE_pk" PRIMARY KEY ("ID_UNI")
);
-- ddl-end --
ALTER TABLE public."TBL_UNIVERSIDADE" OWNER TO postgres;
-- ddl-end --

-- object: public."TBL_CONSU" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_CONSU" CASCADE;
CREATE TABLE public."TBL_CONSU" (
	"ID_CON" smallint NOT NULL,
	"REGIMENTO_INTERNO_CON" varchar(50) NOT NULL,
	"RECOMENDACOES_CON" varchar(50),
	CONSTRAINT "TBL_CONSU_pk" PRIMARY KEY ("ID_CON")
);
-- ddl-end --
ALTER TABLE public."TBL_CONSU" OWNER TO postgres;
-- ddl-end --

-- object: public."TBL_RESOLUCAO" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_RESOLUCAO" CASCADE;
CREATE TABLE public."TBL_RESOLUCAO" (
	"ID_RESO" smallint NOT NULL,
	"NUMERO_RESO" varchar(20) NOT NULL,
	"DESCRICAO_RESO" text NOT NULL,
	"DATA_RESO" date NOT NULL,
	"ID_CON_TBL_CONSU" smallint NOT NULL,
	CONSTRAINT "TBL_RESOLUCAO_pk" PRIMARY KEY ("ID_RESO")
);
-- ddl-end --
ALTER TABLE public."TBL_RESOLUCAO" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_CONSU_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_RESOLUCAO" DROP CONSTRAINT IF EXISTS "TBL_CONSU_fk" CASCADE;
ALTER TABLE public."TBL_RESOLUCAO" ADD CONSTRAINT "TBL_CONSU_fk" FOREIGN KEY ("ID_CON_TBL_CONSU")
REFERENCES public."TBL_CONSU" ("ID_CON") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_CONSU_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_UNIVERSIDADE" DROP CONSTRAINT IF EXISTS "TBL_CONSU_fk" CASCADE;
ALTER TABLE public."TBL_UNIVERSIDADE" ADD CONSTRAINT "TBL_CONSU_fk" FOREIGN KEY ("ID_CON_TBL_CONSU")
REFERENCES public."TBL_CONSU" ("ID_CON") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_UNIVERSIDADE_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_UNIVERSIDADE" DROP CONSTRAINT IF EXISTS "TBL_UNIVERSIDADE_uq" CASCADE;
ALTER TABLE public."TBL_UNIVERSIDADE" ADD CONSTRAINT "TBL_UNIVERSIDADE_uq" UNIQUE ("ID_CON_TBL_CONSU");
-- ddl-end --

-- object: public."TBL_CALEN_REUN_CONSU" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_CALEN_REUN_CONSU" CASCADE;
CREATE TABLE public."TBL_CALEN_REUN_CONSU" (
	"ID_CALEN_REUN_CONSU" smallint NOT NULL,
	"DATA_CALEN_REUN_CONSU" date NOT NULL,
	"HORA_CALEN_REUN_CONSU" varchar(50) NOT NULL,
	"DIA_SEMANA_CALEN_REUN_CONSU" varchar(50) NOT NULL,
	"ID_CON_TBL_CONSU" smallint NOT NULL,
	CONSTRAINT "TBL_CALEN_REUN_CONSU_pk" PRIMARY KEY ("ID_CALEN_REUN_CONSU")
);
-- ddl-end --
ALTER TABLE public."TBL_CALEN_REUN_CONSU" OWNER TO postgres;
-- ddl-end --

-- object: public."TBL_EDITAL" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_EDITAL" CASCADE;
CREATE TABLE public."TBL_EDITAL" (
	"ID_EDITAL" smallint NOT NULL,
	"NUMERO_EDITAL" bigint NOT NULL,
	"DESCRICAO_EDITAL" text NOT NULL,
	"DATA_EDITAL" date NOT NULL,
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_EDITAL_pk" PRIMARY KEY ("ID_EDITAL")
);
-- ddl-end --
ALTER TABLE public."TBL_EDITAL" OWNER TO postgres;
-- ddl-end --

-- object: public."TBL_PORTARIA" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_PORTARIA" CASCADE;
CREATE TABLE public."TBL_PORTARIA" (
	"ID_PORT" smallint NOT NULL,
	"NUMERO_PORT" bigint NOT NULL,
	"DESCRICAO_PORT" text NOT NULL,
	"DATA_PORT" date NOT NULL,
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_PORTARIA_pk" PRIMARY KEY ("ID_PORT")
);
-- ddl-end --
ALTER TABLE public."TBL_PORTARIA" OWNER TO postgres;
-- ddl-end --

-- object: public."TBL_REITORIA" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_REITORIA" CASCADE;
CREATE TABLE public."TBL_REITORIA" (
	"ID_REIT" smallint NOT NULL,
	"EMAIL_REIT" varchar(50) NOT NULL,
	"DESCRICAO_REIT" text NOT NULL,
	"TELEFONE_REIT" varchar(50) NOT NULL,
	CONSTRAINT "TBL_REITORIA_pk" PRIMARY KEY ("ID_REIT")
);
-- ddl-end --
ALTER TABLE public."TBL_REITORIA" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_EDITAL" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_EDITAL" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_PORTARIA" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_PORTARIA" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_PRO_REITORIA" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_PRO_REITORIA" CASCADE;
CREATE TABLE public."TBL_PRO_REITORIA" (
	"ID_PRO_REITORIA" smallint NOT NULL,
	"NOME_PRO_REITORIA" varchar(50) NOT NULL,
	"EMAIL_PRO_REITORIA" varchar(50) NOT NULL,
	"TELEFONE_PRO_REITORIA" varchar(50) NOT NULL,
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_PRO_REITORIA_pk" PRIMARY KEY ("ID_PRO_REITORIA")
);
-- ddl-end --
ALTER TABLE public."TBL_PRO_REITORIA" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_PRO_REITORIA" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_PRO_REITORIA" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_PRO_REITOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_PRO_REITOR" CASCADE;
CREATE TABLE public."TBL_PRO_REITOR" (
	"ID_PRO_REITOR" smallint NOT NULL,
	"NOME_PRO_REITOR" varchar(50) NOT NULL,
	"EMAIL_PRO_REITOR" varchar(50) NOT NULL,
	"DATA_INICIO_MANDATO_PRO_REITOR" date NOT NULL,
	"AREA_ATUACAO_PRO_REITOR" varchar(50) NOT NULL,
	"TELEFONE_PRO_REITOR" varchar(50) NOT NULL,
	"DATA_FIM_MANDATO_PRO_REITOR" date,
	"ID_PRO_REITORIA_TBL_PRO_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_PRO_REITOR_pk" PRIMARY KEY ("ID_PRO_REITOR")
);
-- ddl-end --
ALTER TABLE public."TBL_PRO_REITOR" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_PRO_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_PRO_REITOR" DROP CONSTRAINT IF EXISTS "TBL_PRO_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_PRO_REITOR" ADD CONSTRAINT "TBL_PRO_REITORIA_fk" FOREIGN KEY ("ID_PRO_REITORIA_TBL_PRO_REITORIA")
REFERENCES public."TBL_PRO_REITORIA" ("ID_PRO_REITORIA") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_PRO_REITOR_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_PRO_REITOR" DROP CONSTRAINT IF EXISTS "TBL_PRO_REITOR_uq" CASCADE;
ALTER TABLE public."TBL_PRO_REITOR" ADD CONSTRAINT "TBL_PRO_REITOR_uq" UNIQUE ("ID_PRO_REITORIA_TBL_PRO_REITORIA");
-- ddl-end --

-- object: public."TBL_VICE_REITOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_VICE_REITOR" CASCADE;
CREATE TABLE public."TBL_VICE_REITOR" (
	"ID_VICE_REITOR" smallint NOT NULL,
	"NOME_VICE_REITOR" varchar(50) NOT NULL,
	"DATA_INICIO_MANDATO_VICE_REITOR" date NOT NULL,
	"AREA_ATUACAO_VICE_REITOR" varchar(50) NOT NULL,
	"DATA_FIM_MANDATO_VICE_REITOR" date,
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_VICE_REITOR_pk" PRIMARY KEY ("ID_VICE_REITOR","ID_REIT_TBL_REITORIA")
);
-- ddl-end --
ALTER TABLE public."TBL_VICE_REITOR" OWNER TO postgres;
-- ddl-end --

-- object: public."TBL_CONSEPE" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_CONSEPE" CASCADE;
CREATE TABLE public."TBL_CONSEPE" (
	"ID_CONSEPE" smallint NOT NULL,
	"PAUTA_REUNIAO_CONSEPE" varchar(50) NOT NULL,
	"RECOMENDAÇAO_CONSEPE" varchar(100),
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	"ID_CALEN_REUN_TBL_CALEN_REUN_CONSEPE" smallint NOT NULL,
	CONSTRAINT "TBL_CONSEPE_pk" PRIMARY KEY ("ID_CONSEPE")
);
-- ddl-end --
ALTER TABLE public."TBL_CONSEPE" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_CONSEPE" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_CONSEPE" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_CONSEPE_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_CONSEPE" DROP CONSTRAINT IF EXISTS "TBL_CONSEPE_uq" CASCADE;
ALTER TABLE public."TBL_CONSEPE" ADD CONSTRAINT "TBL_CONSEPE_uq" UNIQUE ("ID_REIT_TBL_REITORIA");
-- ddl-end --

-- object: public."TBL_CALEN_REUN_CONSEPE" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_CALEN_REUN_CONSEPE" CASCADE;
CREATE TABLE public."TBL_CALEN_REUN_CONSEPE" (
	"ID_CALEN_REUN" smallint NOT NULL,
	"DATA_CALEN_REUN" date NOT NULL,
	"HORA_CALEN_REU" varchar(50) NOT NULL,
	"DIA_SEMANA_CALEN_REUN" varchar(50) NOT NULL,
	"ID_CON_TBL_CONSU" smallint NOT NULL,
	CONSTRAINT "TBL_CALEN_REUN_pk_cp" PRIMARY KEY ("ID_CALEN_REUN")
);
-- ddl-end --
ALTER TABLE public."TBL_CALEN_REUN_CONSEPE" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_CONSU_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_CALEN_REUN_CONSU" DROP CONSTRAINT IF EXISTS "TBL_CONSU_fk" CASCADE;
ALTER TABLE public."TBL_CALEN_REUN_CONSU" ADD CONSTRAINT "TBL_CONSU_fk" FOREIGN KEY ("ID_CON_TBL_CONSU")
REFERENCES public."TBL_CONSU" ("ID_CON") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_CALEN_REUN_CONSEPE_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_CONSEPE" DROP CONSTRAINT IF EXISTS "TBL_CALEN_REUN_CONSEPE_fk" CASCADE;
ALTER TABLE public."TBL_CONSEPE" ADD CONSTRAINT "TBL_CALEN_REUN_CONSEPE_fk" FOREIGN KEY ("ID_CALEN_REUN_TBL_CALEN_REUN_CONSEPE")
REFERENCES public."TBL_CALEN_REUN_CONSEPE" ("ID_CALEN_REUN") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_DEPARTAMENTOS" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_DEPARTAMENTOS" CASCADE;
CREATE TABLE public."TBL_DEPARTAMENTOS" (
	"ID_DEP" smallint NOT NULL,
	"NOME_DEP" varchar(50) NOT NULL,
	"EMAIL_DEP" varchar(50) NOT NULL,
	"TELEFONE_DEP" varchar(50) NOT NULL,
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_DEPARTAMENTOS_pk" PRIMARY KEY ("ID_DEP")
);
-- ddl-end --
ALTER TABLE public."TBL_DEPARTAMENTOS" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_DEPARTAMENTOS" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_DEPARTAMENTOS" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_DIRETOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_DIRETOR" CASCADE;
CREATE TABLE public."TBL_DIRETOR" (
	"ID_DIRETOR" smallint NOT NULL,
	"NOME_DIRETOR" varchar(50) NOT NULL,
	"EMAIL_DIRETOR" varchar(50) NOT NULL,
	"DATA_INICIO_MANDATO_DIRETOR" date NOT NULL,
	"DATA_FIM_MANDATO_DIRETOR" date,
	"AREA_ATUACAO_DIRETOR" varchar(50) NOT NULL,
	"TELEFONE_DIRETOR" varchar(50) NOT NULL,
	"ID_DEP_TBL_DEPARTAMENTOS" smallint NOT NULL,
	CONSTRAINT "TBL_DIRETOR_pk" PRIMARY KEY ("ID_DIRETOR")
);
-- ddl-end --
ALTER TABLE public."TBL_DIRETOR" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_DEPARTAMENTOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_DIRETOR" DROP CONSTRAINT IF EXISTS "TBL_DEPARTAMENTOS_fk" CASCADE;
ALTER TABLE public."TBL_DIRETOR" ADD CONSTRAINT "TBL_DEPARTAMENTOS_fk" FOREIGN KEY ("ID_DEP_TBL_DEPARTAMENTOS")
REFERENCES public."TBL_DEPARTAMENTOS" ("ID_DEP") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_DIRETOR_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_DIRETOR" DROP CONSTRAINT IF EXISTS "TBL_DIRETOR_uq" CASCADE;
ALTER TABLE public."TBL_DIRETOR" ADD CONSTRAINT "TBL_DIRETOR_uq" UNIQUE ("ID_DEP_TBL_DEPARTAMENTOS");
-- ddl-end --

-- object: public."TBL_VICE_DIRETOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_VICE_DIRETOR" CASCADE;
CREATE TABLE public."TBL_VICE_DIRETOR" (
	"ID_VICE_DIRETOR" smallint NOT NULL,
	"NOME_VICE_DIRETOR" varchar(50) NOT NULL,
	"EMAIL_VICE_DIRETOR" varchar(50) NOT NULL,
	"DATA_INICIO_MANDATO_VICE_DIRETOR" date NOT NULL,
	"DATA_FIM_MANDATO_VICE_DIRETOR" date,
	"AREA_ATUACAO_VICE_DIRETOR" varchar(50) NOT NULL,
	"TELEFONE_VICE_`DIRETOR" varchar(50) NOT NULL,
	"ID_DEP_TBL_DEPARTAMENTOS" smallint NOT NULL,
	"ID_DEP_TBL_DEPARTAMENTOS1" smallint NOT NULL,
	CONSTRAINT "TBL_DIRETOR_pk_cp" PRIMARY KEY ("ID_VICE_DIRETOR"),
	CONSTRAINT "TBL_DIRETOR_uq_cp" UNIQUE ("ID_DEP_TBL_DEPARTAMENTOS")
);
-- ddl-end --
ALTER TABLE public."TBL_VICE_DIRETOR" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_DEPARTAMENTOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_VICE_DIRETOR" DROP CONSTRAINT IF EXISTS "TBL_DEPARTAMENTOS_fk" CASCADE;
ALTER TABLE public."TBL_VICE_DIRETOR" ADD CONSTRAINT "TBL_DEPARTAMENTOS_fk" FOREIGN KEY ("ID_DEP_TBL_DEPARTAMENTOS1")
REFERENCES public."TBL_DEPARTAMENTOS" ("ID_DEP") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_VICE_DIRETOR_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_VICE_DIRETOR" DROP CONSTRAINT IF EXISTS "TBL_VICE_DIRETOR_uq" CASCADE;
ALTER TABLE public."TBL_VICE_DIRETOR" ADD CONSTRAINT "TBL_VICE_DIRETOR_uq" UNIQUE ("ID_DEP_TBL_DEPARTAMENTOS1");
-- ddl-end --

-- object: public."TBL_PROFESSORES" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_PROFESSORES" CASCADE;
CREATE TABLE public."TBL_PROFESSORES" (
	"ID_PROF" smallint NOT NULL,
	"NOME_PROF" varchar(50) NOT NULL,
	"EMAIL_PROF" varchar(50) NOT NULL,
	"FORMACAO_PROF" text,
	"LATTES_PROF" varchar(150) NOT NULL,
	"ID_DEP_TBL_DEPARTAMENTOS" smallint NOT NULL,
	CONSTRAINT "TBL_PROFESSORES_pk" PRIMARY KEY ("ID_PROF")
);
-- ddl-end --
ALTER TABLE public."TBL_PROFESSORES" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_DEPARTAMENTOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_PROFESSORES" DROP CONSTRAINT IF EXISTS "TBL_DEPARTAMENTOS_fk" CASCADE;
ALTER TABLE public."TBL_PROFESSORES" ADD CONSTRAINT "TBL_DEPARTAMENTOS_fk" FOREIGN KEY ("ID_DEP_TBL_DEPARTAMENTOS")
REFERENCES public."TBL_DEPARTAMENTOS" ("ID_DEP") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_COLEGIADOS" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_COLEGIADOS" CASCADE;
CREATE TABLE public."TBL_COLEGIADOS" (
	"ID_COL" smallint NOT NULL,
	"NOME_COL" varchar(50) NOT NULL,
	"EMAIL_COL" varchar(50) NOT NULL,
	"TELEFONE_COL" varchar(30) NOT NULL,
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_COLEGIADOS_pk" PRIMARY KEY ("ID_COL")
);
-- ddl-end --
ALTER TABLE public."TBL_COLEGIADOS" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_COLEGIADOS" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_COLEGIADOS" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_CURSOS" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_CURSOS" CASCADE;
CREATE TABLE public."TBL_CURSOS" (
	"ID_CURSO" smallint NOT NULL,
	"NOME_CURSO" varchar(50) NOT NULL,
	"ID_COL_TBL_COLEGIADOS" smallint NOT NULL,
	CONSTRAINT "TBL_CURSOS_pk" PRIMARY KEY ("ID_CURSO")
);
-- ddl-end --
ALTER TABLE public."TBL_CURSOS" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_COLEGIADOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_CURSOS" DROP CONSTRAINT IF EXISTS "TBL_COLEGIADOS_fk" CASCADE;
ALTER TABLE public."TBL_CURSOS" ADD CONSTRAINT "TBL_COLEGIADOS_fk" FOREIGN KEY ("ID_COL_TBL_COLEGIADOS")
REFERENCES public."TBL_COLEGIADOS" ("ID_COL") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_COORDENADOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_COORDENADOR" CASCADE;
CREATE TABLE public."TBL_COORDENADOR" (
	"ID_COORD" smallint NOT NULL,
	"NOME_COORD" varchar(50) NOT NULL,
	"EMAIL_COORD" varchar(50) NOT NULL,
	"DATA_INICIO_MANDATO_COORD" date NOT NULL,
	"DATA_FIM_MANDATO_COORD" date,
	"LATTES_LINK_COORD" varchar(150) NOT NULL,
	"ID_COL_TBL_COLEGIADOS" smallint NOT NULL,
	CONSTRAINT "TBL_COORDENADOR_pk" PRIMARY KEY ("ID_COORD")
);
-- ddl-end --
ALTER TABLE public."TBL_COORDENADOR" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_COLEGIADOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_COORDENADOR" DROP CONSTRAINT IF EXISTS "TBL_COLEGIADOS_fk" CASCADE;
ALTER TABLE public."TBL_COORDENADOR" ADD CONSTRAINT "TBL_COLEGIADOS_fk" FOREIGN KEY ("ID_COL_TBL_COLEGIADOS")
REFERENCES public."TBL_COLEGIADOS" ("ID_COL") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_COORDENADOR_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_COORDENADOR" DROP CONSTRAINT IF EXISTS "TBL_COORDENADOR_uq" CASCADE;
ALTER TABLE public."TBL_COORDENADOR" ADD CONSTRAINT "TBL_COORDENADOR_uq" UNIQUE ("ID_COL_TBL_COLEGIADOS");
-- ddl-end --

-- object: public."TBL_VICE_COORDENADOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_VICE_COORDENADOR" CASCADE;
CREATE TABLE public."TBL_VICE_COORDENADOR" (
	"ID_VICE_COORD" smallint NOT NULL,
	"NOME_VICE_COORD" varchar(50) NOT NULL,
	"EMAIL_VICE_COORD" varchar(50) NOT NULL,
	"DATA_INICIO_MANDATO_VICE_COORD" date NOT NULL,
	"DATA_FIM_MANDATO_VICE_COORD" date,
	"LATTES_LINK_VICE_COORD" varchar(150) NOT NULL,
	"ID_COL_TBL_COLEGIADOS" smallint NOT NULL,
	CONSTRAINT "TBL_VICE_COORDENADOR_pk" PRIMARY KEY ("ID_VICE_COORD")
);
-- ddl-end --
ALTER TABLE public."TBL_VICE_COORDENADOR" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_COLEGIADOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_VICE_COORDENADOR" DROP CONSTRAINT IF EXISTS "TBL_COLEGIADOS_fk" CASCADE;
ALTER TABLE public."TBL_VICE_COORDENADOR" ADD CONSTRAINT "TBL_COLEGIADOS_fk" FOREIGN KEY ("ID_COL_TBL_COLEGIADOS")
REFERENCES public."TBL_COLEGIADOS" ("ID_COL") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_VICE_COORDENADOR_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_VICE_COORDENADOR" DROP CONSTRAINT IF EXISTS "TBL_VICE_COORDENADOR_uq" CASCADE;
ALTER TABLE public."TBL_VICE_COORDENADOR" ADD CONSTRAINT "TBL_VICE_COORDENADOR_uq" UNIQUE ("ID_COL_TBL_COLEGIADOS");
-- ddl-end --

-- object: public."TBL_DISCIPLINAS" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_DISCIPLINAS" CASCADE;
CREATE TABLE public."TBL_DISCIPLINAS" (
	"ID_DISC" smallint NOT NULL,
	"NOME_DISC" varchar(50) NOT NULL,
	"CREDITOS_DISC" smallint NOT NULL,
	"CONTEUDO_PROGRAMATICO" text NOT NULL,
	"CARGA_HORARIA" varchar(10) NOT NULL,
	"ID_DEP_TBL_DEPARTAMENTOS" smallint NOT NULL,
	"ID_CURSO_TBL_CURSOS" smallint NOT NULL,
	CONSTRAINT "TBL_DISCIPLINAS_pk" PRIMARY KEY ("ID_DISC")
);
-- ddl-end --
ALTER TABLE public."TBL_DISCIPLINAS" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_DEPARTAMENTOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_DISCIPLINAS" DROP CONSTRAINT IF EXISTS "TBL_DEPARTAMENTOS_fk" CASCADE;
ALTER TABLE public."TBL_DISCIPLINAS" ADD CONSTRAINT "TBL_DEPARTAMENTOS_fk" FOREIGN KEY ("ID_DEP_TBL_DEPARTAMENTOS")
REFERENCES public."TBL_DEPARTAMENTOS" ("ID_DEP") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_CURSOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_DISCIPLINAS" DROP CONSTRAINT IF EXISTS "TBL_CURSOS_fk" CASCADE;
ALTER TABLE public."TBL_DISCIPLINAS" ADD CONSTRAINT "TBL_CURSOS_fk" FOREIGN KEY ("ID_CURSO_TBL_CURSOS")
REFERENCES public."TBL_CURSOS" ("ID_CURSO") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."TBL_ALUNOS" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_ALUNOS" CASCADE;
CREATE TABLE public."TBL_ALUNOS" (
	"ID_ALUNO" smallint NOT NULL,
	"NOME_ALUNO" varchar(100) NOT NULL,
	"EMAIL_ALUNO" varchar(50) NOT NULL,
	"CPF_ALUNO" varchar(50) NOT NULL,
	"DATA_NASCIMENTO_ALUNO" date NOT NULL,
	"ANO_ENTRADA_SEMESTRE" varchar(40) NOT NULL,
	"ID_CURSO_TBL_CURSOS" smallint NOT NULL,
	CONSTRAINT "TBL_ALUNOS_pk" PRIMARY KEY ("ID_ALUNO")
);
-- ddl-end --
ALTER TABLE public."TBL_ALUNOS" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_CURSOS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_ALUNOS" DROP CONSTRAINT IF EXISTS "TBL_CURSOS_fk" CASCADE;
ALTER TABLE public."TBL_ALUNOS" ADD CONSTRAINT "TBL_CURSOS_fk" FOREIGN KEY ("ID_CURSO_TBL_CURSOS")
REFERENCES public."TBL_CURSOS" ("ID_CURSO") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_ALUNOS_uq" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_ALUNOS" DROP CONSTRAINT IF EXISTS "TBL_ALUNOS_uq" CASCADE;
ALTER TABLE public."TBL_ALUNOS" ADD CONSTRAINT "TBL_ALUNOS_uq" UNIQUE ("ID_CURSO_TBL_CURSOS");
-- ddl-end --

-- object: public."TBL_REITOR" | type: TABLE --
-- DROP TABLE IF EXISTS public."TBL_REITOR" CASCADE;
CREATE TABLE public."TBL_REITOR" (
	"ID_REITOR" smallint NOT NULL,
	"NOME_REITOR" varchar(50) NOT NULL,
	"DATA_INICIO_MANDATO_REITOR" date NOT NULL,
	"AREA_ATUACAO_REITOR" varchar(50) NOT NULL,
	"DATA_FIM_MANDATO_REITOR" date,
	"ID_REIT_TBL_REITORIA" smallint NOT NULL,
	CONSTRAINT "TBL_REITOR_pk" PRIMARY KEY ("ID_REITOR","ID_REIT_TBL_REITORIA")
);
-- ddl-end --
ALTER TABLE public."TBL_REITOR" OWNER TO postgres;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_REITOR" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_REITOR" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: "TBL_REITORIA_fk" | type: CONSTRAINT --
-- ALTER TABLE public."TBL_VICE_REITOR" DROP CONSTRAINT IF EXISTS "TBL_REITORIA_fk" CASCADE;
ALTER TABLE public."TBL_VICE_REITOR" ADD CONSTRAINT "TBL_REITORIA_fk" FOREIGN KEY ("ID_REIT_TBL_REITORIA")
REFERENCES public."TBL_REITORIA" ("ID_REIT") MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --


